name: 'Vowel Frequency Analyzer'
description: 'Custom action to analyze the frequency of vowels in a given text file.'

inputs:
  file:
    description: 'The path to the text file to analyze.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run Vowel Frequency Analyzer
      shell: bash
      run: |
        python3 .github/scripts/frequency.py ${{ inputs.file }}
