name: Analyze Vowel Frequency
on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Vowel Frequency Analyzer
        id: analyze_vowels
        uses: ./.github/actions/vowel-frequency-analyzer
        with:
          file: 'data.txt'

      - name: Capture Vowel Frequency Result
        id: freq_result
        run: |
          result=$(python3 .github/scripts/frequency.py 'data.txt')
          echo "FREQ_RESULT=$result" >> $GITHUB_ENV

      - name: Update README with Vowel Frequency
        run: |
          bash .github/scripts/update_readme.sh "$FREQ_RESULT" "$GITHUB_ACTOR"
