name: Analyze Vowel Frequency
on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Vowel Frequency Analyzer
        id: vowel_freq
        run: |
          # Run the frequency.py script to calculate the vowel frequency
          FREQ_RESULT=$(python3 .github/scripts/frequency.py 'data.txt')
          echo "Captured Frequency Result: $FREQ_RESULT"
          echo "FREQ_RESULT=$FREQ_RESULT" >> $GITHUB_ENV

      - name: Update README with Vowel Frequency
        run: |
          echo "FREQ_RESULT=${{ env.FREQ_RESULT }}"
          echo "GITHUB_USER=${{ github.actor }}"

          if [[ -z "${{ env.FREQ_RESULT }}" || -z "${{ github.actor }}" ]]; then
            echo "Error: Missing frequency result or GitHub user."
            exit 1
          fi

          # Now call the update_readme.sh script
          bash .github/scripts/update_readme.sh "${{ env.FREQ_RESULT }}" "${{ github.actor }}"
