name: Analyze Vowel Frequency
on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Vowel Frequency Analyzer
        id: vowel_freq
        uses: ./.github/actions/vowel-frequency-analyzer
        with:
          file: 'data.txt'

      - name: Capture Vowel Frequency Result
        id: capture_freq
        run: |
          # Run the frequency analysis and capture the result
          FREQ_RESULT=$(python3 .github/scripts/frequency.py 'data.txt')
          echo "FREQ_RESULT=$FREQ_RESULT" >> $GITHUB_ENV
          echo "Captured frequency result: $FREQ_RESULT"

      - name: Update README with Vowel Frequency
        run: |
          # Make sure we have the captured frequency result and the GitHub username
          if [[ -z "${{ env.FREQ_RESULT }}" || -z "${{ github.actor }}" ]]; then
            echo "Error: Missing frequency result or GitHub user."
            exit 1
          fi
          bash .github/scripts/update_readme.sh "${{ env.FREQ_RESULT }}" "${{ github.actor }}"
